# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libxml2 \
    libxslt1.1 \
    && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY pyproject.toml README.md server.py client.py .env.example ./
COPY tools ./tools
COPY utils ./utils

# Install Python dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir \
       uvicorn>=0.24.0 starlette>=0.27.0 \
       requests>=2.31.0 \
       mcp[cli]>=1.2.1 \
       openai>=1.61.0 \
       langchain-mcp-adapters>=0.0.5 \
       langgraph>=0.3.16 \
       langchain-openai>=0.3.9 \
       fastmcp>=0.4.1 \
       python-dotenv>=1.0.1

# Expose nothing (stdio server)
# Default command
CMD ["python", "server.py"]
